### ISSUE TITLE
Requests for 10818

### ISSUE THREAD

**Issue by koe7** [gigyesik/baekjoon_python#1]
## comments
- Please implement `main` function
  - I recommend you get input in the main function
  - You might want to let the main function be outside of the `minmax` function
- Please add a parameter in all the functions except for `main`
- You can omit `end=' '` in print
- You can use `map` function when cast `List<str>` to `List<int>` instead of the for loop

Please resolve this issue after applying this comments & getting passed.
If you want, feel free to add the screenshot you passed in this thread.

**Comment by gigyesik** [comment]
I got it.
