### ISSUE TITLE
Feedbacks to 4344 & 15596

### ISSUE THREAD

**Issue by koe7** [gigyesik/baekjoon_python#2]
## 4344
- You shouldn't use `list` as a variable name. It is a reserved keyword.
- Please remove `else: pass`. (It is quite redundant)
- You don't need to use int() to list[0]. You already make it int.
- Nit: you could assign n = list[0] in the first line of the solution function for readability.

## 15596
Also here, the int(a[i]) is unnecessary(you already used map(int, ...) in the main function)

** You can iterate a container(list, set, ...) without indexing.
e.g.)
```
for i in a:
    ans += i
```
And I want to recommend you search the usage of `enumerate` in Google

**Comment by gigyesik** [comment]
change the code as your feedback.
I misunderstood for statement, tried again.
Thanks.
