### ISSUE TITLE
Minor comments for 4673

### ISSUE THREAD

**Issue by koe7** [gigyesik/baekjoon_python#3]
In the main function, you can simplify the for loop, without using the index, as I suggested in the previous comment. (You already did well in the function `d` ...)

The function `d` looks great. You can also implement the code without using the `str` function.(Try it!)

The function `underselfnum`, you've already implemented it very well, but it will be helpful if you refer to the one I made below.
```
def underselfnum(n: int) -> list:
    result = [True] * n
    result[0] = False
    result[1] = True
    for i in range(1, n):
        if d(i) < n:
            result[d(i)] = False
    return result

def main():
    n = 10000
    result = underselfnum(n)
    for i in range(n):
        if result[i]:
            print(i)
```

**Comment by gigyesik** [comment]
I got it.
in def d, I don't know did it well.
Thanks.
